name: pill_reminder_app

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  remove_alpha_ios: true

description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.13.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_local_notifications: ^22.3.0
  timezone: ^0.11.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_riverpod: ^2.6.1
  provider: ^6.1.5+1
  shared_preferences: ^2.5.5
  flutter_timezone: ^5.1.0
  path_provider: ^2.1.5
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/icon/app_icon.png